// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadRuiWenUrl(arg1) {
  return window['go']['main']['App']['DownloadRuiWenUrl'](arg1);
}

export function DownloadUrl(arg1, arg2) {
  return window['go']['main']['App']['DownloadUrl'](arg1, arg2);
}

export function GetDefaultSaveDirectory() {
  return window['go']['main']['App']['GetDefaultSaveDirectory']();
}

export function GetDownloadOutput() {
  return window['go']['main']['App']['GetDownloadOutput']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}
